//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFacilityMaini.DAL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceResponse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceResponse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IFacilityMaini.DAL.Resource.ResourceResponse", typeof(ResourceResponse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Added Successfully.
        /// </summary>
        public static string AddedSuccessMessage {
            get {
                return ResourceManager.GetString("AddedSuccessMessage", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to No New Face Detected.
        /// </summary>
        public static string NoNewFaceDetected
        {
            get
            {
                return ResourceManager.GetString("NoNewFaceDetected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Approved Successful.
        /// </summary>
        public static string ApprovedSuccessful {
            get {
                return ResourceManager.GetString("ApprovedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name and EmailId Already Exists.
        /// </summary>
        public static string ContactExists {
            get {
                return ResourceManager.GetString("ContactExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Deleted Successfully.
        /// </summary>
        public static string DeletedSuccessMessage {
            get {
                return ResourceManager.GetString("DeletedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure you want to Delete this Record?.
        /// </summary>
        public static string DeleteThisRecord {
            get {
                return ResourceManager.GetString("DeleteThisRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate details discarded successfully.
        /// </summary>
        public static string DiscardSuccessMessage {
            get {
                return ResourceManager.GetString("DiscardSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Uploaded Successfully.
        /// </summary>
        public static string DocumentUploadedSuccessful {
            get {
                return ResourceManager.GetString("DocumentUploadedSuccessful", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Document Uploaded Successfully.
        /// </summary>
        public static string DSRUploaderSuccess
        {
            get
            {
                return ResourceManager.GetString("DSRUploaderSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Document Uploaded Successfully.
        /// </summary>
        public static string DSRUploaderFailure
        {
            get
            {
                return ResourceManager.GetString("DSRUploaderFailure", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to No candidates found in list.
        /// </summary>
        public static string ExcelUploadCandidatesNotFound {
            get {
                return ResourceManager.GetString("ExcelUploadCandidatesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocoured please contact system admin.
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Not Updated.
        /// </summary>
        public static string FailureMessage {
            get {
                return ResourceManager.GetString("FailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload a file.
        /// </summary>
        public static string FileUploaderFailure {
            get {
                return ResourceManager.GetString("FileUploaderFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded successful.
        /// </summary>
        public static string FileUploaderSuccess {
            get {
                return ResourceManager.GetString("FileUploaderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check with link.
        /// </summary>
        public static string LinkError {
            get {
                return ResourceManager.GetString("LinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link expired.
        /// </summary>
        public static string LinkTimedOut {
            get {
                return ResourceManager.GetString("LinkTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful.
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Un Successful.
        /// </summary>
        public static string LoginUnSuccessful {
            get {
                return ResourceManager.GetString("LoginUnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Successful.
        /// </summary>
        public static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Un Successful.
        /// </summary>
        public static string LogoutUnSuccessful {
            get {
                return ResourceManager.GetString("LogoutUnSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Sent Successful.
        /// </summary>
        public static string MailSentSuccessful {
            get {
                return ResourceManager.GetString("MailSentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Organization Exists For This User.
        /// </summary>
        public static string NoOrganizationExistsForThisUser {
            get {
                return ResourceManager.GetString("NoOrganizationExistsForThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Successful.
        /// </summary>
        public static string PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("PasswordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide candidateId.
        /// </summary>
        public static string ProvideCandidateId {
            get {
                return ResourceManager.GetString("ProvideCandidateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide next to stage.
        /// </summary>
        public static string ProvideNextToStage {
            get {
                return ResourceManager.GetString("ProvideNextToStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Record is associated with other data and cannot be deleted and can be Archieved.
        /// </summary>
        public static string ReccordAssociated {
            get {
                return ResourceManager.GetString("ReccordAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Updated Successfully.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Updated Successfully.
        /// </summary>
        public static string UpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("UpdatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Does Not Exists.
        /// </summary>
        public static string UserDoesNotExists {
            get {
                return ResourceManager.GetString("UserDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Exists.
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Does Not Exists.
        /// </summary>
        public static string UserNameDoesNotExists {
            get {
                return ResourceManager.GetString("UserNameDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Already Exists.
        /// </summary>
        public static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Name Already Exists.
        /// </summary>
        public static string LoginAgain
        {
            get
            {
                return ResourceManager.GetString("LoginAgain", resourceCulture);
            }
        }
    }
}
